### PR TITLE
Multiple Keys integration + Rotational Keys

### PR DESCRIPTION
**Pull request by RayBytes**
This pull request is still not fully done, but following features will be added:

- [X] Rotational Accounts
- [X] Locking/Unlocking Keys
- [x] Intergration into the rest of the code
- [ ] Full setup.py if needed

### CODE REVIEW

**Comment by RayBytes** [comment]
Alright I think this is pretty much good.

**Comment by RayBytes** [comment]
I also don't think a new setup.py is also needed at this time, since mongodb should be setup externally

**Comment by nsde** [comment]
Thank you, I'll take a look soon :)

**Comment by nsde** [comment]
I'll merge this and then check the code and re-write it. Thanks again for the submission.

**Pull request merged**
